### ISSUE TITLE
When moving, the title of the adjacent tab is visible

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos5-firefox-theme#1]
Hey.

When moved, the main tab becomes transparent and you can see the title of the adjacent tab.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/mCpcSm6/111.png" alt="111" border="0"></a>
When moving in the opposite direction, this problem is not.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/6yDBP30/222.png" alt="222" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'></a><br />

This is also the case in the previous [version](https://github.com/Zonnev/elementaryos-firefox-theme).

**Comment by Zonnev** [comment]
Hello, thanks for reporting the issue, somehow the css styling for it remained in the userChrome. I deleted it, you can install the new userChrome where in its fixed.

**Comment by Zbergen-cli** [comment]
Thank you!

**Comment by Zonnev** [comment]
I fixed it for private mode too. Private mode has transparent tab backgrounds but now the tabs have a solid background when moving them.

**Comment by Zbergen-cli** [comment]
So much better!
