### ISSUE TITLE
The dropdown menu color stands out from the overall theme

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos5-firefox-theme#2]
This is the only drop-down menu where the title color stands out from the overall theme.
![Ekrankopita je 2020-11-19 10 01 32](https://user-images.githubusercontent.com/72291366/99616175-557d7380-2a4f-11eb-8df2-2d4ac837599c.png)

**Comment by Zonnev** [comment]
Hello, I can not theme this because the arrow is part of a shadow-root, which isn't reachable by userChrome.

**Comment by Zbergen-cli** [comment]
It turns out that this is possible. This will recolor all arrows.

```
.panel-arrow {
    fill: var(--arrowpanel-background) !important;
    stroke: var(--arrowpanel-border-color) !important;
}
```

**Comment by Zonnev** [comment]
Your CSS changes all panel arrows, I needed to reach only the specific panel arrow but its impossible...

**Comment by Zbergen-cli** [comment]
Sure, but shouldn't they look the same?

**Comment by Zonnev** [comment]
I wanted to make it a grey gradient, different from the other arrow content menu's. I will look into it later, now I'm working on the Odin theme.

**Comment by Zonnev** [comment]
Hi, I changed the drop down menu but not yet committed it. Just checking if you would like this:
![Schermafdruk van 2020-11-21 19-47-26](https://user-images.githubusercontent.com/32688765/99885099-d779c200-2c32-11eb-9aa4-1262bfa54ba6.png)
![Schermafdruk van 2020-11-21 19-52-57](https://user-images.githubusercontent.com/32688765/99885158-40f9d080-2c33-11eb-8a0f-683488251338.png)
If you don't like it then let me know what to change.

**Comment by Zonnev** [comment]
I have removed the lines and kept the gradient. You can install the latest userChrome.

**Comment by Zbergen-cli** [comment]
Looks awesome! Thanks!
