### ISSUE TITLE
Change the light of the loading indicator in private mode

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos5-firefox-theme#3]
In private mode, the page loading indicator is difficult to see
![Ekrankopita je 2020-11-19 10 21 03](https://user-images.githubusercontent.com/72291366/99617155-439cd000-2a51-11eb-98e3-c976a82a35fa.png)

**Comment by Zonnev** [comment]
Fixed this and more in the new userChrome!
