### ISSUE TITLE
Buttons in the library have no borders

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos5-firefox-theme#4]
Plus, when I hover over them, the text shifts a little to the side.
![Ekrankopita je 2020-11-19 10 38 01](https://user-images.githubusercontent.com/72291366/99618413-d9d1f580-2a53-11eb-81d0-eca55d8c7ce1.png)

**Comment by Zonnev** [comment]
Fixed it in the new userChrome!
