### ISSUE TITLE
Enlarge icons in the bookmark menu

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos5-firefox-theme#5]
Poorly visible due to small size
![Ekrankopita je 2020-11-19 11 46 58](https://user-images.githubusercontent.com/72291366/99622754-5d441480-2a5d-11eb-8284-37a55f9f5aaf.png)
It looks better
```
.subviewbutton > .menu-right {
    width: 1.2em !important;
    height: 1.2em !important;
}
```

![Ekrankopita je 2020-11-19 11 48 11](https://user-images.githubusercontent.com/72291366/99622842-819ff100-2a5d-11eb-9c3e-f63d23c012ff.png)

**Comment by Zonnev** [comment]
I have different icons for menu right:
![Schermafdruk van 2020-11-19 09 40 18](https://user-images.githubusercontent.com/32688765/99642071-5c09ec00-2a4b-11eb-8a87-32e70173a184.png)
Maybe you are using an extension?

**Comment by Zbergen-cli** [comment]
This firefox based build has some bugs. Excuse for troubling.
