### ISSUE TITLE
Font is not visible in the address bar

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos5-firefox-theme#6]
The latest update caused an issue with font display in private mode.
![Ekrankopita je 2020-11-19 18 37 19](https://user-images.githubusercontent.com/72291366/99661627-b54b3d00-2a96-11eb-810c-ccee713e0f1b.png)

**Comment by Zonnev** [comment]
I have no problem with the background of megabar. Sorry to say but maybe it's an issue of your build.

**Comment by Zbergen-cli** [comment]
This problem occurred specifically on firefox 83

**Comment by Zonnev** [comment]
I checked all userChrome files by installing and testing them one by one on Firefox 83 but I don't see what you showed. What I styled are the links in the megabar to white and the whole box should have a gradient background. Also the box should have four round corners, this is what I don't see in your example. 

Btw, I don't use Firefox flatpak version for testing, could this be the problem?

**Comment by Zbergen-cli** [comment]
I would have thought that the problem is in my minor edits, but no. After the last update, I see that the problem is gone. Thanks for your hard work!
