### ISSUE TITLE
Theme not applying with photon layout

### ISSUE THREAD

**Issue by jmbmkn** [Zonnev/elementaryos5-firefox-theme#8]
I'm using eOS 5.1.7 and the flatpak Firefox which is at version 89.0 and when I opened it at first with the theme applied it looked a it off so I ran the command from the readme and restarted Firefox. Now I have proton tabs below an elementary looking address bar but the menu and other icons are no themed. Not sure what step I missed.
![image](https://user-images.githubusercontent.com/402149/120863372-53f64180-c582-11eb-828f-071e5ad3eb79.png)

**Comment by Zonnev** [comment]
Sorry!!! I forgot to end the new CSS code with }, so the following tab code wasn't applied anymore... The new userChrome for the default layout is fixed.

**Comment by jmbmkn** [comment]
Awesome, reapplied and it's working as expected and looking great
